version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: producer
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
    depends_on:
      - kafka
  batch-consumer:
    build:
      context: .
      dockerfile: consumers/Dockerfile.batch
    container_name: batch-consumer
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      PYTHONUNBUFFERED: "1"
    env_file:
      - .env 
    restart: unless-stopped
    depends_on:
      - kafka
  live-state-consumer:
    build:
      context: .
      dockerfile: consumers/Dockerfile.live
    container_name: live-batch-consumer
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      REDIS_HOST: redis
      PYTHONUNBUFFERED: "1" 
    restart: unless-stopped
    depends_on:
      - kafka
      - redis  
  
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    environment:
      REDIS_HOST: redis
      PYTHONUNBUFFERED: "1" 
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data/station_info.json:/app/data/station_info.json:ro
    restart: unless-stopped
    depends_on:
      - redis  
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5500:80"
    depends_on:
      - backend 
volumes:
  kafka-data: